name: TWRP Builder

on:
  workflow_dispatch:

jobs:
  build:
    name: Build TWRP for Rodin
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y git-core gnupg flex bison build-essential zip curl zlib1g-dev gcc-multilib g++-multilib \
            libc6-dev-i386 lib32ncurses5-dev x11proto-core-dev libx11-dev lib32z-dev ccache libgl1-mesa-dev libxml2-utils \
            xsltproc unzip python3 python-is-python3

      - name: Set up repo
        run: |
          mkdir -p ~/bin
          curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
          chmod a+x ~/bin/repo
          echo 'export PATH=~/bin:$PATH' >> $GITHUB_ENV

      - name: Initialize TWRP source
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          mkdir -p ~/twrp
          cd ~/twrp
          repo init -u https://github.com/minimal-manifest-twrp/platform_manifest_twrp_aosp.git -b twrp-12.1
          repo sync -j$(nproc) --force-sync

      - name: Download and extract device tree (ZIP)
        run: |
          cd ~/twrp/device/xiaomi
          mkdir -p rodin
          wget https://github.com/tiixman/twrp_builder_rodin/releases/download/1.0/device_tree_Poco_x7_pro.zip -O tree.zip
          unzip tree.zip -d rodin

      - name: Build TWRP
        run: |
          cd ~/twrp
          . build/envsetup.sh
          lunch twrp_rodin-eng
          mka recoveryimage

      - name: Package with AnyKernel3
        run: |
          cd ~
          git clone https://github.com/osm0sis/AnyKernel3
          cp ~/twrp/out/target/product/rodin/recovery.img ~/AnyKernel3/recovery.img
          cd ~/AnyKernel3
          zip -r9 twrp-rodin.zip * -x .git README.md

      - name: Upload TWRP ZIP
        uses: actions/upload-artifact@v3
        with:
          name: twrp-rodin
          path: ~/AnyKernel3/twrp-rodin.zip
