name: TWRP Builder

on:
  workflow_dispatch:

jobs:
  build:
    name: Build TWRP for Rodin
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y git gh curl zip unzip git-core gnupg flex bison build-essential \
            zlib1g-dev gcc-multilib g++-multilib libc6-dev-i386 lib32ncurses5-dev \
            libx11-dev lib32z-dev ccache libgl1-mesa-dev libxml2-utils xsltproc

      - name: Set up repo tool
        run: |
          mkdir -p ~/bin
          curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
          chmod a+x ~/bin/repo
          echo "$HOME/bin" >> $GITHUB_PATH

      - name: Initialize TWRP source
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          mkdir -p ~/twrp
          cd ~/twrp
          repo init -u https://github.com/minimal-manifest-twrp/platform_manifest_twrp_aosp.git -b twrp-12.1
          repo sync -j$(nproc) --force-sync

      - name: Download and extract device tree (ZIP)
        run: |
          mkdir -p ~/twrp/device/xiaomi/rodin
          cd ~/twrp/device/xiaomi
          wget https://github.com/tiixman/twrp_builder_rodin/releases/download/1.0/device_tree_Poco_x7_pro.zip -O tree.zip
          unzip tree.zip -d temp_tree
          mv temp_tree/rodin/* rodin/
          rm -rf temp_tree tree.zip

      - name: Build TWRP
        run: |
          cd ~/twrp
          . build/envsetup.sh
          lunch twrp_rodin-eng
          mka recoveryimage

      - name: Package with AnyKernel3
        run: |
          cd ~
          git clone https://github.com/osm0sis/AnyKernel3
          cp ~/twrp/out/target/product/rodin/recovery.img ~/AnyKernel3/recovery.img
          cd ~/AnyKernel3
          zip -r9 twrp-rodin.zip * -x .git README.md

      - name: Upload to Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        working-directory: ~/AnyKernel3
        run: |
          TAG="auto-$(date +%Y%m%d-%H%M)"
          gh release create "$TAG" twrp-rodin.zip -t "TWRP for Rodin - $TAG" -n "Automated build"
